# Generated by Django 3.0.8 on 2020-07-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccode', models.IntegerField()),
                ('Cdescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ltitle', models.CharField(help_text='Choose a title for your listing', max_length=50)),
                ('Ccode', models.IntegerField(help_text='Categories Ex: 1-Apartament,2-Commercial,3-Farm, 4-House ')),
                ('Ldescription', models.CharField(max_length=250)),
                ('Lprice', models.FloatField(help_text='starting bid Just USD')),
                ('Ldatestart', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>. for the auction start')),
                ('Lduration', models.IntegerField(help_text='Duration expressed in days')),
                ('Luser', models.CharField(max_length=25)),
                ('Limage', models.ImageField(blank=True, upload_to='images')),
                ('Lstatus', models.CharField(choices=[('A', 'Active'), ('B', 'To Begin'), ('C', 'Closed'), ('S', 'Sold')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wflag', models.IntegerField()),
                ('user', models.CharField(max_length=25)),
                ('Lcode', models.ForeignKey(help_text='Choose a title from listing', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings')),
            ],
        ),
    
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buser', models.CharField(max_length=25)),
                ('Bthrow', models.IntegerField()),
                ('Bprice', models.FloatField(help_text='Just USD')),
                ('Bdate', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('Lcode', models.ForeignKey(help_text='Choose a title from listing', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings')),
            ],
        ),
    ]
