# Generated by Django 3.0.8 on 2020-07-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelistings_bids_categories_comments_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
