# Generated by Django 3.0.8 on 2020-07-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200716_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldTo',
        ),
    ]
