# Generated by Django 3.0.8 on 2020-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200723_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Ccomment',
            field=models.TextField(max_length=250),
        ),
    ]
