# Generated by Django 3.0.8 on 2020-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelistings_bids_categories_comments_listings_soldto_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bprice',
            field=models.FloatField(help_text='Just USD'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(help_text='Just USD'),
        ),
        migrations.AlterField(
            model_name='soldto',
            name='Bprice',
            field=models.FloatField(help_text='Just USD'),
        ),
    ]
